### ISSUE TITLE
How do I ignore a specific Discord user?

### ISSUE THREAD

**Issue by deathspawn** [copygirl/cord#10]
The wiki doesn't state how to ignore a Discord username. I've tried adding discord:username, discord:username#0000, discord:#0000, discord:@username, on both of the ignore settings and still messages get relayed.

Edit: Also tried discord:000 and still relaying.

Edit 2: The user is a bot, not sure if that makes any difference.

**Comment by copygirl** [comment]
Currently only the numeric user ID works I think (if at all), which you can do in Discord by enabling developer mode, right clicking and choosing "Copy ID", as far as I can see. I will try to fix this to allow for `discord:username#discriminator`.

**edit:** Appears to be `discord:@<id>` currently.

**Comment by copygirl** [comment]
Took a go at it today and can't really get in the debugging mindset. Maybe I'll try tomorrow.

**Comment by deathspawn** [comment]
I tried to use discord:@0000 and no go. Even tried using the user ID both with @ and without it and still messages get passed through. For reference, the 0000 is the number that comes after the name when you right click a user and hit profile.

**Comment by copygirl** [comment]
> For reference, the 0000 is the number that comes after the name when you right click a user and hit profile.

That is not the numeric ID I was talking about, that's just the discriminator. For example, cord's ID is `108188740794474496`. But I tried ignoring my Discord user to no avail.

**Comment by copygirl** [comment]
Let me know if this fixes the problem. Testing it on my end, it seems like it did the job,
